### ISSUE TITLE
Saving Events Twice Creates Two Events

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/austese_repository#19]
When editing Events, saving twice (without navigating back to Events) has created duplicate Events. Deleting duplicate has been the solution so far.

**Comment by AnnaGerber** [comment]
Duplicate of #14
This issue was fixed in https://github.com/uq-eresearch/austese_repository/commit/47ca59ddd170f2892557901ec836b7d2cd00f662 (but probably hadn't been deployed to austese.net at the point that this bug was reported)
